backend:
  name: github
  repo: matthewkeil/CODEified
  branch: master
  site_domain: codeified.org
  base_url: https://nomad-devops.nomad.house/v1
  auth_endpoint: auth
local_backend: true
publish_mode: editorial_workflow
media_folder: '@/static/media'
public_folder: '@/static/media'
site_url: https://www.codeified.org
collections:
  - name: categories
    label: Categories
    folder: assets/content/categories
    create: true
    slug: '{{slug}}'
    identified_field: name
    fields:
      - { label: Name, name: name, widget: string }
      - {
          label: Description,
          name: description,
          widget: markdown,
          required: false,
        }
  - name: posts
    label: Posts
    folder: assets/content/posts
    preview_path: '{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - { name: author, label: Author, widget: string }
      - { name: hero, lable: Hero Image, widget: image }
      - {
          name: prominent,
          lable: Prominent,
          widget: boolean,
          default: false,
          required: false,
        }
      - {
          name: published,
          label: Publish Date,
          widget: datetime,
          default: true,
          required: true,
        }
      - {
          name: updated,
          label: Updated Date,
          widget: datetime,
          default: true,
          required: false,
        }
      - { name: body, label: Body, widget: markdown }
      - {
          label: Category,
          name: category,
          widget: relation,
          collection: categories,
          searchFields: name,
          valueField: name,
          multiple: true,
        }
