backend:
  name: git-gateway
  repo: nomad-house
  branch: master
  site_domain: nomad.house
  base_url: https://github.com
  auth_endpoint: auth
local_backend: true
publish_mode: editorial_workflow
media_folder: static/media
public_folder: static/public
site_url: https://nomad.house
collections:
  - name: categories
    label: Categories
    folder: content/categories
    create: true
    slug: '{{slug}}'
    identified_field: name
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Description, name: description, widget: markdown }
  - name: posts
    label: Posts
    folder: content/posts
    preview_path: '{{slug}}'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { label: Layout, name: layout, widget: hidden, default: blog }
      - { label: Title, name: title, widget: string }
      - { label: Subtitle, name: subtitle, widget: string }
      - { label: Author, name: author, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { lable: Feature Image, name: featureImage, widget: image }
      - { label: Body, name: body, widget: markdown }
      - {
          label: Category,
          name: category,
          widget: relation,
          collection: categories,
          searchFields: name,
          valueField: name,
          multiple: true,
        }
